// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4BvxWgFur0awW2Ug7iUZx5X71Xq2IA2o',
    appId: '1:207216575695:web:ec60644517b61a5810e3ba',
    messagingSenderId: '207216575695',
    projectId: 'chat-app-481ae',
    authDomain: 'chat-app-481ae.firebaseapp.com',
    databaseURL: 'https://chat-app-481ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-481ae.appspot.com',
    measurementId: 'G-WPVQ0V91MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2py2kpeNxcArBFpaGkupPnrWZpKb2NN0',
    appId: '1:207216575695:android:7e549d1d0ad063bf10e3ba',
    messagingSenderId: '207216575695',
    projectId: 'chat-app-481ae',
    databaseURL: 'https://chat-app-481ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-481ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQlFBluoZLfJ6g1x86Ih8mlWa8CHOjVs',
    appId: '1:207216575695:ios:81e911db92b76bd710e3ba',
    messagingSenderId: '207216575695',
    projectId: 'chat-app-481ae',
    databaseURL: 'https://chat-app-481ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-481ae.appspot.com',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQlFBluoZLfJ6g1x86Ih8mlWa8CHOjVs',
    appId: '1:207216575695:ios:81e911db92b76bd710e3ba',
    messagingSenderId: '207216575695',
    projectId: 'chat-app-481ae',
    databaseURL: 'https://chat-app-481ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-481ae.appspot.com',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4BvxWgFur0awW2Ug7iUZx5X71Xq2IA2o',
    appId: '1:207216575695:web:281229dbabd5ccb110e3ba',
    messagingSenderId: '207216575695',
    projectId: 'chat-app-481ae',
    authDomain: 'chat-app-481ae.firebaseapp.com',
    databaseURL: 'https://chat-app-481ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-481ae.appspot.com',
    measurementId: 'G-4E89GYQRQC',
  );
}
